<a href="https://colab.research.google.com/github/yna2131/SemanaTec/blob/main/actividad06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Actividad - Estadística básica**

* **Nombre:** Yuna Chung
* **Matrícula:** A01709043

**Entregar:** Archivo PDF de la actividad, así como el archivo .ipynb en tu repositorio. **Nota:** Recuerda habrá una penalización de **50** puntos si la actividad fue entregada fuera de la fecha límite.

Carga el conjunto de datos `insurance.csv` (se encuentra en el repositorio de la clase) y realiza un análisis estadístico de las variables.

In [ ]:
# Carga las librerías necesarias.

import pandas as pd
import numpy as np
import random
from scipy import stats
from scipy.stats import pearsonr

In [ ]:
# Carga el conjunto de datos al ambiente de Google Colab y muestra los primeros
# 6 renglones.

from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('user uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))

df = pd.read_csv('insurance.csv')
df.head(6)

Saving insurance.csv to insurance.csv
user uploaded file "insurance.csv" with length 54289 bytes

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160

El conjunto de datos contiene información demográfica sobre los asegurados en una compañía de seguros:

* **age:** Edad del asegurado principal
* **sex:** Género del asegurado. female o male
* **bmi:** Índice de masa corporal
* children: Número de hijos que estan cubiertos con la poliza.
* **smoke:** ¿El beneficiario fuma? (*yes/no*)
* **region:** ¿Dónde vive el beneficiario? Estos datos son de Estados Unidos. Regiones disponibles: northeast, southeast, southwest, northwest
* **charges:** Costo del seguro.

In [ ]:
# Crea una tabla resumen con los estadísticas generales de las variables
# numéricas.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
# ¿Cómo se correlacionan las varaibles numéricas entre sí?

df.corr()

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [ ]:
# Determina si existe o no una correlación entre el índice de masa corporal 
# (bmi) y el costo del seguro.

select = df[['bmi', 'charges']]
select.corr()

print('Correlación Pearson: ', 
      select['bmi'].corr(select['charges'], method = 'pearson'))

Correlación Pearson:  0.19834096883362895

In [ ]:
# ¿Cuántas personas aseguradas son hombre y cuántas son mujeres?

df['sex'].value_counts()

male      676
female    662
Name: sex, dtype: int64

In [ ]:
# ¿Cuántos hombres y mujeres asegurados viven en cada región?

pd.crosstab(df['sex'], df['region'])

region  northeast  northwest  southeast  southwest
sex
female        161        164        175        162
male          163        161        189        163

In [ ]:
# En promedio, ¿quién paga más de cuota de seguro? ¿Los fumadores o los no 
# fumadores? Muéstralo con los datos.

df.groupby('smoker').mean()[['charges']]

             charges
smoker
no       8434.268298
yes     32050.231832

In [ ]:
# ¿Cuáles son las cuotas mínimas y máximas que las personan pagan dependiendo
# del género y del número de hijos?

df.groupby(['sex', 'children']).agg(['min', 'max'])[['charges']]

                    charges
                        min          max
sex    children
female 0         1607.51010  63770.42801
       1         2201.09710  58571.07448
       2         2801.25880  47305.30500
       3         4234.92700  46661.44240
       4         4561.18850  36580.28216
       5         4687.79700  19023.26000
male   0         1121.87390  62592.87309
       1         1711.02680  51194.55914
       2         2304.00220  49577.66240
       3         3443.06400  60021.39897
       4         4504.66240  40182.24600
       5         4915.05985  14478.33015

In [ ]:
# ¿Cuál es el índice de masa corporal promedio para hombre y mujeres dependiendo
# región en la que viven y si son fumadores? ¿Impacta eso en la tarifa del 
# seguro?

impact = df.groupby(['sex', 'smoker', 'region']).mean()[['bmi', 'charges']]
impact

                               bmi       charges
sex    smoker region
female no     northeast  29.777462   9640.426984
              northwest  29.488704   8786.998679
              southeast  32.780000   8440.205552
              southwest  30.050355   8234.091260
       yes    northeast  27.261724  28032.046398
              northwest  28.296897  29670.824946
              southeast  32.251389  33034.820716
              southwest  30.128571  31687.988430
male   no     northeast  28.861760   8664.042222
              northwest  28.930379   8320.689321
              southeast  34.129552   7609.003587
              southwest  31.019841   7778.905534
       yes    northeast  29.560000  30926.252583
              northwest  29.983966  30713.181419
              southeast  33.650000  36029.839367
              southwest  31.502703  32598.862854